version: '3.5'
services:
  robs-adventures:
    build: .
    volumes:
      - .:/src
    ports:
      - '8080:8080'
    command: npm start
    environment:
      NODE_ENV: production
      PORT: 8080
