name: Stage

on:
  push:
    branches:
      - stage
 
jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with: 
          node-version: '16.17.0'
      - name: Install Node Dependecies
        run: npm ci
      - name: Run Build
        run: npm run build